"""
Proactive re-engagement messages for students who've gone quiet — separate
from anything triggered by an actual incoming chat turn (see
app.services.chat_core). Three rotating types:

- "fun_fact": a short, punchy NCERT-grounded "Did you know?" line for the
  student's own class/subject, generated by the LLM from a REAL retrieved
  textbook chunk (see app.services.retrieval) — never an ungrounded LLM
  guess, so it can't invent something wrong. Skipped for a class/board with
  no ingested content yet (see scripts/bulk_ingest_pdfs.py): thin coverage
  should silently drop this nudge type, not send a made-up "fact".
- "feature_highlight": a rotating call-out of a feature this student has
  access to but hasn't actually used yet (voice notes, photo homework,
  documents, video explanations) — the point is discovery, so a feature
  they've already used or don't have access to is skipped.
- "social_proof": Qlass's own real, already-published marketing claims
  (from qlasslearning.com) — deliberately NOT invented numbers. Never
  attribute a stat to Qlass that isn't one Qlass has actually published.

scripts/send_engagement_nudges.py is the actual cron entry point that
calls pick_next_nudge per inactive student and sends the result.
"""
import random
from datetime import datetime, timedelta, timezone

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.models.core import Student
from app.services.llm_client import call_llm

FUN_FACT_MODEL = "claude-haiku-4-5-20251001"  # short, narrow task — cheap tier is enough

# WhatsApp requires an approved template to message a student outside an
# active 24h session (see the OTP saga in app.services.otp for the same
# constraint) — a re-engagement nudge is by definition to someone who's
# gone quiet, so it's always outside that window. Needs a real Marketing-
# category template submitted via the Wati dashboard with exactly one body
# variable ({{1}}) carrying the nudge text itself, e.g.:
#   "Hi! {{1}} — Your Qlass AI Tutor"
# A variable can't be the first or last thing in the body (Meta rejects
# that) — there must be real static text on both sides.
# Blank/unapproved template name here means scripts/send_engagement_nudges.py
# simply can't send yet — not a code bug, an external approval step.
ENGAGEMENT_NUDGE_TEMPLATE_NAME = "student_engagement_nudge"

# A type sent recently doesn't repeat until this many days have passed —
# keeps the rotation varied rather than the same type every single nudge.
NUDGE_COOLDOWN_DAYS = 7

NUDGE_TYPES = ["fun_fact", "feature_highlight", "social_proof"]

# (feature key in Student.features, one-line pitch). Order is the rotation
# priority when more than one is eligible — voice/photo first since they're
# the most viscerally different from typing a question.
FEATURE_HIGHLIGHTS: list[tuple[str, str]] = [
    ("voice", "🎙️ Did you know you can just *send a voice note* instead of typing? Ask your next question out loud!"),
    ("ocr", "📸 Stuck on a textbook question? Snap a *photo* and send it — I'll read it and explain the answer."),
    ("youtube_videos", "📺 Some topics click faster with a video — just ask, and I'll find the best explanation for it."),
    ("documents", "📄 You can send me a *PDF or Word file* of your homework and I'll help you work through it."),
    ("image_generation", "🎨 Ask me to *draw a diagram* next time you're studying something visual — I can sketch it out for you."),
]

# Qlass's own real, already-published marketing claims and case-study
# details (qlasslearning.com) — reused verbatim/near-verbatim rather than
# invented, so nothing claimed here is a number Qlass hasn't actually
# stood behind publicly.
SOCIAL_PROOF_MESSAGES: list[str] = [
    "🌟 Qlass students have gone from 40% to 88% in just 45 days. Keep showing up — that could be you!",
    "🚀 You're one of 10,000+ students learning with Qlass across India. Let's keep your streak going!",
    "🧠 Students who practice regularly with Qlass show 2× faster retention and 3× longer recall. Consistency is the real secret.",
    "⏱️ Your AI tutor is here 24×7 with under 30-second replies — no doubt has to wait until tomorrow.",
    "📈 One Qlass student went 45% → 92% in 45 days: Day 14 was \"concepts click, doubts cleared,\" Day 28 hit a 75% mock score. Small consistent days add up.",
    "🗣️ You can talk to me in Hindi, Bhojpuri, and 10+ other languages — voice-enabled, so language is never the thing standing between you and understanding.",
    "✅ 92% of consistent Qlass students hit their target scores. Today's question could be part of getting you there.",
]


def _cooldown_cutoff() -> datetime:
    return datetime.now(timezone.utc) - timedelta(days=NUDGE_COOLDOWN_DAYS)


def _eligible_types(student: Student) -> list[str]:
    sent = student.nudges_sent or {}
    cutoff = _cooldown_cutoff()
    eligible = []
    for nudge_type in NUDGE_TYPES:
        last_sent = sent.get(nudge_type)
        if not last_sent:
            eligible.append(nudge_type)
            continue
        last_sent_dt = datetime.fromisoformat(last_sent)
        if last_sent_dt < cutoff:
            eligible.append(nudge_type)
    return eligible


def _next_feature_highlight(db: Session, student: Student) -> str | None:
    """The first feature this student has access to but hasn't paid for a
    usage event on yet (see app.services.cost_tracker's credit_events
    ledger — every voice/OCR/image/video/document use writes a row there)."""
    for feature_key, pitch in FEATURE_HIGHLIGHTS:
        if not student.has_feature(feature_key):
            continue
        service_names = {
            "voice": ("sarvam_tts",), "ocr": ("azure_ocr",), "youtube_videos": ("youtube_search", "youtube_search_overage"),
            "documents": (), "image_generation": ("azure_image",),
        }[feature_key]
        if not service_names:
            # "documents" has no distinct billed service of its own (plain
            # text extraction, no external API cost) — always eligible once
            # the feature flag is on, since there's no usage signal to
            # check against.
            return pitch
        used = db.execute(
            text("SELECT 1 FROM credit_events WHERE student_id = :sid AND service = ANY(:services) LIMIT 1"),
            {"sid": student.id, "services": list(service_names)},
        ).first()
        if used is None:
            return pitch
    return None


async def _generate_fun_fact(db: Session, student: Student) -> str | None:
    if not student.class_:
        return None
    row = db.execute(
        text(
            "SELECT dc.content, d.subject, d.chapter FROM document_chunks dc "
            "JOIN documents d ON d.id = dc.document_id "
            "WHERE d.class = :class_ AND (:board IS NULL OR d.board = :board) "
            "ORDER BY random() LIMIT 1"
        ),
        {"class_": student.class_, "board": student.board},
    ).first()
    if row is None:
        return None
    content, subject, chapter = row
    system_prompt = (
        "You write a single, short, exciting WhatsApp message (max 2 sentences, one relevant emoji) "
        "starting with \"Did you know?\" that shares one genuinely interesting fact drawn ONLY from the "
        "textbook excerpt given. Never add any fact, number, or claim not present in the excerpt. "
        "Write for a curious school student, not a textbook."
    )
    result = await call_llm(
        system_prompt,
        [{"role": "user", "content": f"Subject: {subject}\nChapter: {chapter}\n\nExcerpt:\n{content[:1200]}"}],
        model=FUN_FACT_MODEL,
    )
    return result.text.strip() or None


async def pick_next_nudge(db: Session, student: Student) -> tuple[str, str] | None:
    """
    Returns (nudge_type, message_text) for the next nudge this student
    should get, or None if nothing is eligible right now (every type on
    cooldown, or the only remaining type has no real content to send —
    e.g. fun_fact with no ingested chunks for this student's class, or
    feature_highlight when every enabled feature is already in active use).
    """
    eligible = _eligible_types(student)
    random.shuffle(eligible)  # don't always try the same type first when several are eligible
    for nudge_type in eligible:
        if nudge_type == "feature_highlight":
            message = _next_feature_highlight(db, student)
        elif nudge_type == "social_proof":
            message = random.choice(SOCIAL_PROOF_MESSAGES)
        else:
            message = await _generate_fun_fact(db, student)
        if message:
            return nudge_type, message
    return None


def record_nudge_sent(db: Session, student: Student, nudge_type: str) -> None:
    sent = dict(student.nudges_sent or {})
    sent[nudge_type] = datetime.now(timezone.utc).isoformat()
    student.nudges_sent = sent
    db.commit()
