"""
Proactive re-engagement messages for students who've gone quiet — separate
from anything triggered by an actual incoming chat turn (see
app.services.chat_core). Three rotating types:

- "fun_fact": a short, punchy NCERT-grounded "Did you know?" line for the
  student's own class/subject, generated by the LLM from a REAL retrieved
  textbook chunk (see app.services.retrieval) — never an ungrounded LLM
  guess, so it can't invent something wrong. Skipped for a class/board with
  no ingested content yet (see scripts/bulk_ingest_pdfs.py): thin coverage
  should silently drop this nudge type, not send a made-up "fact".
- "feature_highlight": a rotating call-out of a feature this student has
  access to but hasn't actually used yet (voice notes, photo homework,
  documents, video explanations) — the point is discovery, so a feature
  they've already used or don't have access to is skipped.
- "social_proof": Qlass's own real, already-published marketing claims
  (from qlasslearning.com) — deliberately NOT invented numbers. Never
  attribute a stat to Qlass that isn't one Qlass has actually published.

scripts/send_engagement_nudges.py is the actual cron entry point that
calls pick_next_nudge per inactive student and sends the result. The
template (see ENGAGEMENT_NUDGE_TEMPLATE_NAME) carries a "Know More" Quick
Reply button — get_know_more_reply below is what answers that tap (see
app.routers.whatsapp), tailored to whichever specific nudge was actually
sent, not a generic reply.
"""
import random
from datetime import datetime, timedelta, timezone

from sqlalchemy import text
from sqlalchemy.orm import Session

from app.models.core import Student
from app.services.llm_client import call_llm

FUN_FACT_MODEL = "claude-haiku-4-5-20251001"  # short, narrow task — cheap tier is enough

# WhatsApp requires an approved template to message a student outside an
# active 24h session (see the OTP saga in app.services.otp for the same
# constraint) — a re-engagement nudge is by definition to someone who's
# gone quiet, so it's always outside that window. TWO approved Marketing-
# category templates, both with one body variable ({{1}}, carrying the
# nudge text — a variable can't be the first or last thing in the body,
# Meta rejects that):
#
# - ENGAGEMENT_NUDGE_TEMPLATE_NAME ("student_engagement_nudge"): has a
#   "Know More" Quick Reply button (see get_know_more_reply, called from
#   app.routers.whatsapp when a student taps it) — used ONLY for a
#   "fun_fact" nudge, where tapping it actually goes somewhere.
# - ENGAGEMENT_NUDGE_PLAIN_TEMPLATE_NAME ("student_engagement_nudge_plain"):
#   same body, no button at all — used for feature_highlight/social_proof,
#   where "Know More" wouldn't lead anywhere (a pitch or a marketing claim,
#   not knowledge to go deeper on). Wati has no per-send conditional
#   button on one template, so this needed to be a second, separately
#   submitted template rather than a code-level toggle.
ENGAGEMENT_NUDGE_TEMPLATE_NAME = "student_engagement_nudge"
ENGAGEMENT_NUDGE_PLAIN_TEMPLATE_NAME = "student_engagement_nudge_plain"
KNOW_MORE_BUTTON_TEXT = "Know More"


def template_for_nudge_type(nudge_type: str) -> str:
    return ENGAGEMENT_NUDGE_TEMPLATE_NAME if nudge_type == "fun_fact" else ENGAGEMENT_NUDGE_PLAIN_TEMPLATE_NAME

# A type sent recently doesn't repeat until this many days have passed —
# keeps the rotation varied rather than the same type every single nudge.
NUDGE_COOLDOWN_DAYS = 7

NUDGE_TYPES = ["fun_fact", "feature_highlight", "social_proof"]

# (feature key in Student.features, one-line pitch). Order is the rotation
# priority when more than one is eligible — voice/photo first since they're
# the most viscerally different from typing a question.
FEATURE_HIGHLIGHTS: list[tuple[str, str]] = [
    ("voice", "🎙️ Did you know you can just *send a voice note* instead of typing? Ask your next question out loud!"),
    ("ocr", "📸 Stuck on a textbook question? Snap a *photo* and send it — I'll read it and explain the answer."),
    ("youtube_videos", "📺 Some topics click faster with a video — just ask, and I'll find the best explanation for it."),
    ("documents", "📄 You can send me a *PDF or Word file* of your homework and I'll help you work through it."),
    ("image_generation", "🎨 Ask me to *draw a diagram* next time you're studying something visual — I can sketch it out for you."),
]

# Qlass's own real, already-published marketing claims and case-study
# details (qlasslearning.com) — reused verbatim/near-verbatim rather than
# invented, so nothing claimed here is a number Qlass hasn't actually
# stood behind publicly.
SOCIAL_PROOF_MESSAGES: list[str] = [
    "🌟 Students using Skoolgpt AI have gone from 40% to 88% in just 45 days. Keep showing up — that could be you!",
    "🚀 You're one of 10,000+ students learning with Skoolgpt AI across India. Let's keep your streak going!",
    "🧠 Students who practice regularly with Skoolgpt AI show 2× faster retention and 3× longer recall. Consistency is the real secret.",
    "⏱️ Your Skoolgpt AI tutor is here 24×7 with under 30-second replies — no doubt has to wait until tomorrow.",
    "📈 One Skoolgpt AI student went 45% → 92% in 45 days: Day 14 was \"concepts click, doubts cleared,\" Day 28 hit a 75% mock score. Small consistent days add up.",
    "🗣️ You can talk to your Skoolgpt AI tutor in Hindi, Bhojpuri, and 10+ other languages — voice-enabled, so language is never the thing standing between you and understanding.",
    "✅ 92% of consistent Skoolgpt AI students hit their target scores. Today's question could be part of getting you there.",
]

def _cooldown_cutoff() -> datetime:
    return datetime.now(timezone.utc) - timedelta(days=NUDGE_COOLDOWN_DAYS)


def _parse_sent_entry(entry) -> tuple[datetime, str | None]:
    """
    nudges_sent values used to be a plain ISO timestamp string; now they're
    {"sent_at": ..., "detail": ...} so a "Know More" tap can look up what
    was actually sent (see get_know_more_reply). Reads either shape so
    existing rows written before this change don't break.
    """
    if isinstance(entry, dict):
        return datetime.fromisoformat(entry["sent_at"]), entry.get("detail")
    return datetime.fromisoformat(entry), None


def _eligible_types(student: Student) -> list[str]:
    sent = student.nudges_sent or {}
    cutoff = _cooldown_cutoff()
    eligible = []
    for nudge_type in NUDGE_TYPES:
        entry = sent.get(nudge_type)
        if not entry:
            eligible.append(nudge_type)
            continue
        last_sent_dt, _ = _parse_sent_entry(entry)
        if last_sent_dt < cutoff:
            eligible.append(nudge_type)
    return eligible


def _next_feature_highlight(db: Session, student: Student) -> tuple[str, str] | None:
    """The first feature this student has access to but hasn't paid for a
    usage event on yet (see app.services.cost_tracker's credit_events
    ledger — every voice/OCR/image/video/document use writes a row there).
    Returns (feature_key, pitch) so the caller can record which one."""
    for feature_key, pitch in FEATURE_HIGHLIGHTS:
        if not student.has_feature(feature_key):
            continue
        service_names = {
            "voice": ("sarvam_tts",), "ocr": ("azure_ocr",), "youtube_videos": ("youtube_search", "youtube_search_overage"),
            "documents": (), "image_generation": ("azure_image",),
        }[feature_key]
        if not service_names:
            # "documents" has no distinct billed service of its own (plain
            # text extraction, no external API cost) — always eligible once
            # the feature flag is on, since there's no usage signal to
            # check against.
            return feature_key, pitch
        used = db.execute(
            text("SELECT 1 FROM credit_events WHERE student_id = :sid AND service = ANY(:services) LIMIT 1"),
            {"sid": student.id, "services": list(service_names)},
        ).first()
        if used is None:
            return feature_key, pitch
    return None


NO_FACT_SENTINEL = "NO_FACT"

# How many different random chunks to try before giving up on this cycle —
# a single random chunk is often a word problem's setup line ("Atul is 19,
# Parul is 7") or exercise instructions with no real standalone fact in it,
# so the LLM needs the freedom to reject a bad draw and the caller needs to
# actually retry with a fresh one rather than force a "fact" out of
# whatever it happened to get (confirmed live, Aug 2026 — that's exactly
# what produced the odd age-gap "fact" sent to a real student).
FUN_FACT_MAX_ATTEMPTS = 4


async def _generate_fun_fact(db: Session, student: Student) -> tuple[str, str] | None:
    """Returns (message, chapter) so the chapter can be recorded as this
    nudge's detail — see get_know_more_reply."""
    if not student.class_:
        return None
    rows = db.execute(
        text(
            "SELECT dc.content, d.subject, d.chapter FROM document_chunks dc "
            "JOIN documents d ON d.id = dc.document_id "
            "WHERE d.class = :class_ AND (:board IS NULL OR d.board = :board) "
            "ORDER BY random() LIMIT :limit"
        ),
        {"class_": student.class_, "board": student.board, "limit": FUN_FACT_MAX_ATTEMPTS},
    ).all()
    system_prompt = (
        "You write a single, short, exciting WhatsApp message (max 2 sentences, one relevant emoji) "
        "starting with \"Did you know?\" that shares one genuinely interesting, standalone fact drawn ONLY "
        "from the textbook excerpt given. Never add any fact, number, or claim not present in the excerpt. "
        "Write for a curious school student, not a textbook.\n\n"
        "Many excerpts are just word-problem setups, exercise instructions, or answer keys — these have "
        "NO real fact in them, just incidental numbers or names (e.g. a word problem naming two people's "
        "ages to set up a subtraction question is NOT an interesting fact about age). If the excerpt has "
        f"no genuinely interesting, standalone fact worth sharing, respond with exactly \"{NO_FACT_SENTINEL}\" "
        "and nothing else — do not force a fact out of it."
    )
    for content, subject, chapter in rows:
        result = await call_llm(
            system_prompt,
            [{"role": "user", "content": f"Subject: {subject}\nChapter: {chapter}\n\nExcerpt:\n{content[:1200]}"}],
            model=FUN_FACT_MODEL,
        )
        message = result.text.strip()
        if message and NO_FACT_SENTINEL not in message:
            return message, chapter
    return None


async def pick_next_nudge(db: Session, student: Student) -> tuple[str, str, str | None] | None:
    """
    Returns (nudge_type, message_text, detail) for the next nudge this
    student should get, or None if nothing is eligible right now (every
    type on cooldown, or the only remaining type has no real content to
    send — e.g. fun_fact with no ingested chunks for this student's class,
    or feature_highlight when every enabled feature is already in active
    use). `detail` is what record_nudge_sent should store alongside the
    timestamp, so a later "Know More" tap knows what was actually sent.
    """
    eligible = _eligible_types(student)
    random.shuffle(eligible)  # don't always try the same type first when several are eligible
    for nudge_type in eligible:
        if nudge_type == "feature_highlight":
            picked = _next_feature_highlight(db, student)
            if picked:
                feature_key, message = picked
                return nudge_type, message, feature_key
        elif nudge_type == "social_proof":
            return nudge_type, random.choice(SOCIAL_PROOF_MESSAGES), None
        else:
            picked = await _generate_fun_fact(db, student)
            if picked:
                message, chapter = picked
                return nudge_type, message, chapter
    return None


def record_nudge_sent(db: Session, student: Student, nudge_type: str, detail: str | None = None) -> None:
    sent = dict(student.nudges_sent or {})
    sent[nudge_type] = {"sent_at": datetime.now(timezone.utc).isoformat(), "detail": detail}
    student.nudges_sent = sent
    db.commit()


def get_know_more_reply(student: Student) -> str | None:
    """
    Answers a tap on the nudge template's "Know More" Quick Reply button
    (see app.routers.whatsapp) — but ONLY when the most recent nudge this
    student got was an actual "fun_fact" (real knowledge shared, something
    there's genuinely more to learn about). A feature_highlight or
    social_proof nudge is a pitch, not knowledge — "know more" doesn't
    mean anything there, and the button is on every send regardless of
    type only because it's baked into one shared WhatsApp template (Wati
    doesn't support a per-send conditional button). Returns None for those
    cases so app.routers.whatsapp just lets the tap fall through to normal
    chat instead of forcing a canned reply that doesn't fit.
    """
    sent = student.nudges_sent or {}
    latest_type, latest_dt, latest_detail = None, None, None
    for nudge_type, entry in sent.items():
        dt, detail = _parse_sent_entry(entry)
        if latest_dt is None or dt > latest_dt:
            latest_type, latest_dt, latest_detail = nudge_type, dt, detail

    if latest_type == "fun_fact" and latest_detail:
        return f"Want to go deeper on *{latest_detail}*? Just ask me anything about it — I'm ready when you are! 📚"
    return None
