ALTER TABLE students ADD COLUMN IF NOT EXISTS consecutive_unresolved_hints INTEGER DEFAULT 0;

ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS created_by_teacher_id INTEGER REFERENCES teachers(id);
ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE quizzes ADD COLUMN IF NOT EXISTS is_mock_test BOOLEAN DEFAULT FALSE;
