import { Link } from "react-router-dom";
import LegalLayout, { SUPPORT_WHATSAPP, SUPPORT_WHATSAPP_LINK } from "../components/LegalLayout";

export default function Terms() {
  return (
    <LegalLayout title="Terms of Service">
      <h2>1. Who we are</h2>
      <p>
        Skoolgpt is an AI tutoring service operated by Qlass Edtech ("Qlass", "we", "us"), a company registered in
        India. Registered address: SkoolGPT, 1st and 2nd Floor, Near RPS Engineering College, Kothwan, Khagaul,
        Danapur, Patna, Bihar, India – 801503. GSTIN: 10AAACQ9006D1Z3. These Terms govern your use of Skoolgpt on
        WhatsApp and at skoolgpt.in.
        By using Skoolgpt you agree to them.
      </p>

      <h2>2. Eligibility and parental consent</h2>
      <p>
        Skoolgpt is built for school students. If you are under 18, you may use Skoolgpt only with the consent of a
        parent or legal guardian, who accepts these Terms on your behalf and is responsible for your use of the
        service. A school that enrols its students on Skoolgpt confirms that it has obtained the necessary consent
        from their parents or guardians and is acting on their behalf.
      </p>

      <h2>3. The service</h2>
      <p>
        Skoolgpt answers academic questions sent by text, voice note, photo or document over WhatsApp and the web
        chat, and provides quizzes, worksheets and progress reports. Answers are generated by artificial
        intelligence and may be incomplete, out of date or simply wrong. Skoolgpt is a study aid, not a substitute
        for a teacher, a textbook or a school. Always check important answers against your textbook or with a
        teacher before relying on them, especially for examinations.
      </p>
      <p>
        We may change, suspend or withdraw features at any time. We try to keep the service available around the
        clock but do not guarantee uninterrupted access.
      </p>

      <h2>4. Accounts and phone numbers</h2>
      <p>
        Your Skoolgpt account is tied to the WhatsApp number you register. You must have the right to use that
        number, keep it in your control and tell us if it changes. One-time codes we send to that number are for
        you alone. We may refuse, suspend or close an account that was created with someone else's number or
        false details. A parent may link to a child's account to view progress and billing.
      </p>

      <h2>5. Credits and plans</h2>
      <ul>
        <li>
          <strong>Prepaid credits.</strong> Credits are bought in advance and deducted as you use the tutor. They
          are non-transferable between accounts, have no cash value except as described in our{" "}
          <Link to="/refunds">Refund Policy</Link>, and are consumed at the rates displayed at the time of use.
        </li>
        <li>
          <strong>Annual plans.</strong> The Plus plan gives access for the period shown at purchase and
          renews automatically unless cancelled. It is subject to a fair-use limit displayed at the time of
          purchase and on your account page; usage well beyond what a single student would reasonably need may be
          slowed or paused for the rest of the billing period. Plans are for one student and may not be shared.
        </li>
        <li>
          <strong>Free trial credit</strong> is granted once per verified phone number and may be withdrawn if we
          detect abuse.
        </li>
        <li>Prices are in Indian Rupees, include applicable taxes unless stated otherwise, and may change with notice for future purchases.</li>
      </ul>

      <h2>6. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>send content that is abusive, sexual, hateful, threatening or unlawful, or that targets another person;</li>
        <li>use the tutor to cheat in a live examination or to do work you are required to do unaided;</li>
        <li>attempt to extract the underlying models or prompts, probe or overload our systems, or bypass credit or fair-use limits;</li>
        <li>share your account, resell access, or register with false details or someone else's number.</li>
      </ul>
      <p>Content you send remains yours; you give us permission to process it to provide the service.</p>

      <h2>7. Termination</h2>
      <p>
        You may stop using Skoolgpt at any time and may ask us to delete your account (see the{" "}
        <Link to="/privacy">Privacy Policy</Link>). We may suspend or close an account that breaches these Terms,
        with notice where practical. Unused prepaid credits on an account closed for breach are forfeited; on an
        account closed at your request they are handled under the Refund Policy.
      </p>

      <h2>8. Limitation of liability</h2>
      <p>
        To the fullest extent permitted by Indian law, Skoolgpt is provided "as is". We are not liable for
        academic results, examination outcomes, or losses arising from inaccurate AI answers, WhatsApp or network
        outages, or events outside our reasonable control. Our total liability to you for any claim is limited to
        the amount you paid us in the 12 months before the claim arose. Nothing in these Terms limits liability
        that cannot be limited under the Consumer Protection Act, 2019 or other applicable law.
      </p>

      <h2>9. Changes to these Terms</h2>
      <p>
        We may update these Terms. Material changes will be announced on WhatsApp or on this page before they take
        effect; continuing to use Skoolgpt afterwards means you accept the updated Terms.
      </p>

      <h2>10. Governing law</h2>
      <p>
        These Terms are governed by the laws of India. Subject to any consumer-protection forum you are entitled to
        use, the courts at Patna, Bihar have exclusive jurisdiction over disputes.
      </p>

      <h2>11. Contact</h2>
      <p>
        Questions about these Terms: WhatsApp <a href={SUPPORT_WHATSAPP_LINK}>{SUPPORT_WHATSAPP}</a>.
      </p>
    </LegalLayout>
  );
}
